@echo off
echo Building and deploying duty scheduler...

echo Building client image...
docker build -t nirberkovich/duty-scheduler-client:latest ./client

echo Building server image...
docker build -t nirberkovich/duty-scheduler-server:latest ./server

echo Pushing client image to Docker Hub...
docker push nirberkovich/duty-scheduler-client:latest

echo Pushing server image to Docker Hub...
docker push nirberkovich/duty-scheduler-server:latest

echo Waiting 5 seconds before restarting containers...
timeout /t 5 /nobreak > nul

echo Restarting server container app...
powershell -ExecutionPolicy Bypass -Command "az containerapp update --name server --resource-group Nir --set-env-vars RESTART_AT=%RANDOM%"

echo Restarting client container app...
powershell -ExecutionPolicy Bypass -Command "az containerapp update --name client --resource-group Nir --set-env-vars RESTART_AT=%RANDOM%"

echo Deployment completed!
