BEGIN;
CREATE TABLE IF NOT EXISTS people (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  gender TEXT NOT NULL,
  sameGenderPref INTEGER NOT NULL DEFAULT 0,
  limitedAbility INTEGER NOT NULL DEFAULT 0,
  standingExemption INTEGER NOT NULL DEFAULT 0,
  duelGuard INTEGER NOT NULL DEFAULT 0,
  userId INTEGER
);
CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  requiredPerShift INTEGER NOT NULL DEFAULT 1,
  optional INTEGER NOT NULL DEFAULT 0,
  userId INTEGER
);
CREATE TABLE IF NOT EXISTS assignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  personId INTEGER NOT NULL,
  postId INTEGER NOT NULL,
  day TEXT NOT NULL,
  shiftLabel TEXT NOT NULL,
  startISO TEXT,
  endISO TEXT,
  userId INTEGER
);

CREATE TABLE IF NOT EXISTS bw_assignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  personId INTEGER NOT NULL,
  day TEXT NOT NULL,
  slotId TEXT NOT NULL,
  userId INTEGER
);

CREATE TABLE IF NOT EXISTS es_assignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  groupId TEXT NOT NULL,
  personId INTEGER NOT NULL,
  userId INTEGER
);

CREATE TABLE IF NOT EXISTS constraints (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  personId INTEGER NOT NULL,
  title TEXT NOT NULL,
  startISO TEXT NOT NULL,
  endISO TEXT NOT NULL,
  userId INTEGER
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL
);
COMMIT;
