BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS people (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  gender TEXT NOT NULL,
  sameGenderPref BOOLEAN NOT NULL DEFAULT false,
  limitedAbility BOOLEAN NOT NULL DEFAULT false,
  standingExemption BOOLEAN NOT NULL DEFAULT false,
  duelGuard BOOLEAN NOT NULL DEFAULT false,
  userId INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  requiredPerShift INTEGER NOT NULL DEFAULT 1,
  optional BOOLEAN NOT NULL DEFAULT false,
  userId INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS assignments (
  id SERIAL PRIMARY KEY,
  personId INTEGER NOT NULL,
  postId INTEGER NOT NULL,
  day TEXT NOT NULL,
  shiftLabel TEXT NOT NULL,
  startISO TEXT,
  endISO TEXT,
  userId INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bw_assignments (
  id SERIAL PRIMARY KEY,
  personId INTEGER NOT NULL,
  day TEXT NOT NULL,
  slotId TEXT NOT NULL,
  userId INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS es_assignments (
  id SERIAL PRIMARY KEY,
  groupId TEXT NOT NULL,
  personId INTEGER NOT NULL,
  userId INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS constraints (
  id SERIAL PRIMARY KEY,
  personId INTEGER NOT NULL,
  title TEXT NOT NULL,
  startISO TEXT NOT NULL,
  endISO TEXT NOT NULL,
  userId INTEGER REFERENCES users(id)
);

COMMIT;
